### ISSUE TITLE
HTTP Error 413

### ISSUE THREAD

**Issue by tamboril** [ogrebenyuk/compilerexplorer#1]
While the "Test Connection" works fine for the public server, the plugin is getting "HTTP error code : 413 from https://godbolt.org".

**Comment by ogrebenyuk** [comment]
You must be trying to compile some large source file. Any instance of Compiler Explorer has limits on (a) size and (b) compilation time. When I try some large real projects, I have to increase those limits in my local CE instance, otherwise it fails with errors like 413.
I suggest that you bring up your own local instance and raise those limits in etc/config/compiler-explorer.defaults.properties:
compileTimeoutMs=1000000
max-asm-size=1000000000
